name: Java CI with JUnit

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compile Java code
      run: javac -cp .:junit-4.13.2.jar:hamcrest-core-1.3.jar *.java

    - name: Run Unit Tests
      run: java -cp .:junit-4.13.2.jar:hamcrest-core-1.3.jar org.junit.runner.JUnitCore NumberUtilsTest


